trigger:
  branches:
    include:
      - main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    repository: 'trvloreg.azurecr.io/users'
    dockerfile: 'Users/Dockerfile'
    containerRegistry: 'ACR_SERVICE_CONNECTION'
    tags: |
      $(Build.BuildId)

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'  # Your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group Travelio --name trvloAKSCluster
      kubectl set image deployment/users-deployment users=trvloreg.azurecr.io/users:$(Build.BuildId)
