name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            backend_node/node_modules
          key: node-${{ hashFiles('backend_node/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install Node.js dependencies
        run: |
          cd backend_node
          npm install

      - name: Build Docker image
        run: |
          docker build -t your-image-name:latest -f backend_node/Dockerfile backend_node

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          cd backend_node
          railway up --service Travelio